/* erk.h: the Erk embedding ABI (p1-contract). Generated by cbindgen from
 * crates/erk-ffi; do not edit. A test fails when this copy is out of date. */

#ifndef ERK_H
#define ERK_H

#include <stddef.h>
#include <stdint.h>

/*
 The ABI's version: `(major << 16) | minor`. Within a major version
 functions, constants and trailing structure fields are only added.
 */
#define ERK_ABI_VERSION 7

#define ERK_RESOURCE_IMAGE 1

#define ERK_RESOURCE_STYLESHEET 2

#define ERK_RESOURCE_FONT 3

#define ERK_LOG_ERROR 1

#define ERK_LOG_WARNING 2

#define ERK_LOG_INFO 3

#define ERK_LOG_DEBUG 4

/*
 No window: the host ticks the app, gives it input and reads its frames.
 */
#define ERK_APP_HEADLESS 1

/*
 Draw text with the embedded font only, the same on every machine.
 */
#define ERK_APP_EMBEDDED_FONTS 2

/*
 Draw the window on the CPU even where a GPU is available.
 */
#define ERK_APP_CPU 4

#define ERK_INPUT_POINTER_MOVE 1

#define ERK_INPUT_POINTER_DOWN 2

#define ERK_INPUT_POINTER_UP 3

#define ERK_INPUT_POINTER_LEAVE 4

#define ERK_INPUT_KEY_DOWN 5

#define ERK_INPUT_KEY_UP 6

#define ERK_INPUT_WHEEL 7

#define ERK_BUTTON_NONE 0

#define ERK_BUTTON_PRIMARY 1

#define ERK_BUTTON_SECONDARY 2

#define ERK_BUTTON_MIDDLE 3

#define ERK_KEY_OTHER 0

#define ERK_KEY_TAB 1

#define ERK_KEY_ENTER 2

#define ERK_KEY_SPACE 3

#define ERK_KEY_ESCAPE 4

/*
 The key typed `text`.
 */
#define ERK_KEY_CHARACTER 5

#define ERK_KEY_BACKSPACE 6

#define ERK_MOD_SHIFT 1

#define ERK_MOD_CONTROL 2

#define ERK_MOD_ALT 4

#define ERK_MOD_META 8

#define ERK_EVENT_CLICK 1

#define ERK_EVENT_INPUT 2

#define ERK_EVENT_CHANGE 3

#define ERK_EVENT_SUBMIT 4

#define ERK_EVENT_KEY_DOWN 5

#define ERK_EVENT_KEY_UP 6

#define ERK_EVENT_FOCUS 7

#define ERK_EVENT_BLUR 8

#define ERK_PHASE_CAPTURE 1

#define ERK_PHASE_TARGET 2

#define ERK_PHASE_BUBBLE 3

#define ERK_MUTATION_CREATE_ELEMENT 1

#define ERK_MUTATION_CREATE_TEXT 2

#define ERK_MUTATION_APPEND 3

#define ERK_MUTATION_INSERT_BEFORE 4

#define ERK_MUTATION_REMOVE 5

#define ERK_MUTATION_SET_TEXT 6

#define ERK_MUTATION_SET_ATTR 7

#define ERK_MUTATION_REMOVE_ATTR 8

#define ERK_MUTATION_ADD_CLASS 9

#define ERK_MUTATION_REMOVE_CLASS 10

#define ERK_MUTATION_SET_STYLE_PROPERTY 11

#define ERK_MUTATION_REMOVE_STYLE_PROPERTY 12

#define ERK_NODE_DOCUMENT 1

#define ERK_NODE_ELEMENT 2

#define ERK_NODE_TEXT 3

#define ERK_NODE_COMMENT 4

#define ERK_NODE_OTHER 5

/*
 An app: one document and its window. Opaque.
 */
typedef struct ErkApp ErkApp;

/*
 Text Erk owns: give it back to `erk_string_free`.
 */
typedef struct {
  char *ptr;
  size_t len;
} ErkString;

/*
 What a call did: `ERK_OK`, or why it failed.
 */
typedef int32_t ErkStatus;

/*
 UTF-8 text in: Erk copies it before the call returns. It need not end
 with NUL; `ptr` may be null when `len` is 0.
 */
typedef struct {
  const char *ptr;
  size_t len;
} ErkStr;

/*
 Content asks for a resource (CSS `url()`, `<img>`). Answer now or later,
 from any thread, with `erk_resource_complete`.
 */
typedef void (*ErkResourceFn)(void *user_data,
                              ErkApp *app,
                              uint64_t request,
                              uint32_t kind,
                              ErkStr url);

typedef void (*ErkLogFn)(void *user_data, uint32_t level, ErkStr message);

/*
 What an app starts with. Fields past `struct_size` take their defaults.
 */
typedef struct {
  /*
   `sizeof(ErkConfig)`.
   */
  uint32_t struct_size;
  /*
   The viewport in logical pixels.
   */
  uint32_t width;
  uint32_t height;
  /*
   Device pixels per CSS pixel of a headless app; 0 is 1.
   */
  float scale;
  ErkStr title;
  /*
   May be NULL: no resource loads.
   */
  ErkResourceFn resource;
  void *resource_user_data;
  /*
   May be NULL.
   */
  ErkLogFn log;
  void *log_user_data;
  /*
   The least severe `ERK_LOG_*` the log gets; 0 is `ERK_LOG_WARNING`.
   */
  uint32_t log_level;
  /*
   `ERK_APP_*` flags.
   */
  uint32_t flags;
} ErkConfig;

typedef void (*ErkPostFn)(void *user_data, ErkApp *app);

typedef void (*ErkDestroyFn)(void *user_data);

/*
 Input for a headless app, in CSS pixels. Fields past `struct_size` are 0.
 */
typedef struct {
  uint32_t struct_size;
  /*
   `ERK_INPUT_*`.
   */
  uint32_t kind;
  float x;
  float y;
  /*
   How far a wheel scrolls; positive towards the end of the page.
   */
  float dx;
  float dy;
  /*
   `ERK_BUTTON_*`.
   */
  uint32_t button;
  /*
   `ERK_KEY_*`.
   */
  uint32_t key;
  /*
   The character an `ERK_KEY_CHARACTER` typed.
   */
  ErkStr text;
  /*
   `ERK_MOD_*` bits.
   */
  uint32_t modifiers;
} ErkInput;

/*
 A frame of a headless app: `width` × `height` premultiplied RGBA8
 pixels, valid until the next tick or the app's end.
 */
typedef struct {
  uint32_t struct_size;
  uint32_t width;
  uint32_t height;
  const uint8_t *rgba;
  size_t len;
} ErkFrame;

/*
 A node of an app's document: opaque, meaningful only to the app that
 gave it, never 0. Not a security token.
 */
typedef uint64_t ErkNodeId;

/*
 One change of a batch for `erk_apply`. `node`, `parent` and `before` are
 node ids or `ERK_NEW_NODE + i`.

 - `ERK_MUTATION_CREATE_ELEMENT`: `value` is the tag.
 - `ERK_MUTATION_CREATE_TEXT`: `value` is the text.
 - `ERK_MUTATION_APPEND`: `node` into `parent`, last.
 - `ERK_MUTATION_INSERT_BEFORE`: `node` into `parent` before `before`
   (`ERK_NODE_NONE`: last).
 - `ERK_MUTATION_REMOVE`: `node` and everything in it.
 - `ERK_MUTATION_SET_TEXT`: `node`'s text to `value`.
 - `ERK_MUTATION_SET_ATTR`: attribute `name` of `node` to `value`.
 - `ERK_MUTATION_REMOVE_ATTR`: attribute `name` of `node`.
 - `ERK_MUTATION_ADD_CLASS`, `ERK_MUTATION_REMOVE_CLASS`: class `value`.
 - `ERK_MUTATION_SET_STYLE_PROPERTY`: inline style property `name` of
   `node` to `value`, as `erk_node_set_style_property`.
 - `ERK_MUTATION_REMOVE_STYLE_PROPERTY`: inline style property `name`.
 */
typedef struct {
  /*
   `sizeof(ErkMutation)`: also the stride of the array.
   */
  uint32_t struct_size;
  /*
   `ERK_MUTATION_*`.
   */
  uint32_t kind;
  ErkNodeId node;
  ErkNodeId parent;
  ErkNodeId before;
  ErkStr name;
  ErkStr value;
} ErkMutation;

/*
 An event, valid only during the callback.
 */
typedef struct {
  uint32_t struct_size;
  /*
   `ERK_EVENT_*`; ignore kinds you do not know.
   */
  uint32_t kind;
  /*
   `ERK_PHASE_*`.
   */
  uint32_t phase;
  ErkNodeId target;
  ErkNodeId current_target;
  /*
   Logical pixels, pointer events.
   */
  double x;
  double y;
  /*
   `ERK_MOD_*` bits.
   */
  uint32_t modifiers;
  /*
   Key events: the character typed, for `ERK_KEY_CHARACTER`.
   */
  ErkStr text;
  /*
   Key events: `ERK_KEY_*`.
   */
  uint32_t key;
} ErkEvent;

typedef void (*ErkEventFn)(void *user_data, ErkApp *app, const ErkEvent *event);

/*
 A subscription, to cancel with `erk_off`; never 0.
 */
typedef uint64_t ErkSubscription;

/*
 A node's box in the last frame: the border box in CSS pixels relative to
 the viewport, and the sides, each top, right, bottom, left.
 */
typedef struct {
  uint32_t struct_size;
  float x;
  float y;
  float width;
  float height;
  float margin[4];
  float border[4];
  float padding[4];
} ErkBox;

/*
 How long the last frame's stages took, measured outside the core.
 */
typedef struct {
  uint32_t struct_size;
  uint64_t frame;
  uint64_t style_ns;
  uint64_t layout_ns;
  uint64_t display_list_ns;
  uint64_t raster_ns;
} ErkFrameTimings;

#define ERK_OK 0

/*
 A null pointer, bad UTF-8, a value out of range.
 */
#define ERK_ERR_INVALID_ARGUMENT 1

/*
 The node was removed, belongs to a replaced document or to another app.
 */
#define ERK_ERR_STALE_NODE 2

/*
 Called from a thread other than the app's UI thread; nothing was done.
 */
#define ERK_ERR_WRONG_THREAD 3

/*
 The caller's buffer is too small; `*len` holds the size needed.
 */
#define ERK_ERR_BUFFER_TOO_SMALL 4

#define ERK_ERR_NOT_FOUND 5

/*
 Not allowed inside a callback.
 */
#define ERK_ERR_REENTRANT 6

/*
 The call panicked; the app is now poisoned.
 */
#define ERK_ERR_PANIC 7

/*
 An earlier call panicked; only `erk_app_destroy` works.
 */
#define ERK_ERR_POISONED 8

/*
 The platform could not make the window or run its event loop.
 */
#define ERK_ERR_PLATFORM 9

/*
 No node.
 */
#define ERK_NODE_NONE 0

/*
 A node an earlier mutation of the same batch created, by its position:
 `ERK_NEW_NODE + i` names what mutation `i` created. No real node id is
 this small: a node id's upper half is its generation, never 0.
 */
#define ERK_NEW_NODE 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t erk_abi_version(void);

/*
 Give back a string Erk made. A null string is ignored.
 */
void erk_string_free(ErkString s);

/*
 Make an app on this thread, which becomes its UI thread.
 */
ErkStatus erk_app_create(const ErkConfig *config, ErkApp **out);

/*
 End the app: every subscription's destroy runs once, and its ids go
 stale. Not from inside a callback; works on a poisoned app.
 */
ErkStatus erk_app_destroy(ErkApp *app);

/*
 Erk's event loop: open the window and run until it closes.
 */
ErkStatus erk_app_run(ErkApp *app);

/*
 Run `fn(user_data, app)` on the app's UI thread before its next frame;
 `destroy(user_data)` after it, or when the app ends first. Any thread.
 */
ErkStatus erk_app_post(ErkApp *app, ErkPostFn function, void *user_data, ErkDestroyFn destroy);

/*
 Answer resource request `request`: `ERK_OK` with the bytes and their MIME
 type (empty: from the bytes), any other status for none. Any thread; Erk
 copies the bytes.
 */
ErkStatus erk_resource_complete(ErkApp *app,
                                uint64_t request,
                                ErkStatus result,
                                ErkStr mime,
                                const uint8_t *data,
                                size_t len);

/*
 A turn of a headless app at `now_ns` (§7): what arrived is handled, and a
 frame painted if something that shows has changed.
 */
ErkStatus erk_app_tick(ErkApp *app, uint64_t now_ns);

/*
 Give a headless app input, as a window would.
 */
ErkStatus erk_app_input(ErkApp *app, const ErkInput *input);

/*
 A headless app's last frame; `ERK_ERR_NOT_FOUND` before the first.
 */
ErkStatus erk_app_frame(ErkApp *app, ErkFrame *out);

/*
 Show `html` instead of the document; the old ids go stale.
 */
ErkStatus erk_load_html(ErkApp *app, ErkStr html);

ErkStatus erk_document_root(ErkApp *app, ErkNodeId *out);

/*
 The first element inside `scope` (`ERK_NODE_NONE`: the document)
 matching `selector`; `*out` is `ERK_NODE_NONE` when none does.
 */
ErkStatus erk_query(ErkApp *app, ErkNodeId scope, ErkStr selector, ErkNodeId *out);

/*
 Open a transaction: until the outermost one is committed no frame is
 prepared, so none shows the document halfway through a group of
 changes (p1-contract §10, v0.6). Transactions nest.
 */
ErkStatus erk_transaction_begin(ErkApp *app);

/*
 Close the innermost transaction; `ERK_ERR_INVALID_ARGUMENT` if none is
 open.
 */
ErkStatus erk_transaction_commit(ErkApp *app);

ErkStatus erk_node_set_text(ErkApp *app, ErkNodeId node_id, ErkStr value);

/*
 `node`'s text as `textContent`; `*len` is the bytes needed (no NUL).
 */
ErkStatus erk_node_text(ErkApp *app, ErkNodeId node_id, char *buf, size_t cap, size_t *len);

/*
 A new element named `tag`, not in the document yet: insert it with
 `erk_node_append` or `erk_node_insert_before`, or let it go with
 `erk_node_remove`. HTML lowercases the name.
 */
ErkStatus erk_node_create(ErkApp *app, ErkStr tag, ErkNodeId *out);

/*
 A new text node, not in the document yet.
 */
ErkStatus erk_text_create(ErkApp *app, ErkStr value, ErkNodeId *out);

/*
 Make `child` the last child of `parent`, moving it from wherever it
 was. `ERK_ERR_INVALID_ARGUMENT` where DOM refuses it.
 */
ErkStatus erk_node_append(ErkApp *app, ErkNodeId parent, ErkNodeId child);

/*
 Insert `child` into `parent` before `before`, a child of `parent`, or
 last for `ERK_NODE_NONE`.
 */
ErkStatus erk_node_insert_before(ErkApp *app, ErkNodeId parent, ErkNodeId child, ErkNodeId before);

/*
 Remove `node` and everything in it: their ids go stale and their
 subscriptions end.
 */
ErkStatus erk_node_remove(ErkApp *app, ErkNodeId node_id);

ErkStatus erk_node_set_attr(ErkApp *app, ErkNodeId node_id, ErkStr name, ErkStr value);

/*
 Remove attribute `name`; `ERK_ERR_NOT_FOUND` if there was none.
 */
ErkStatus erk_node_remove_attr(ErkApp *app, ErkNodeId node_id, ErkStr name);

/*
 Attribute `name`'s value; `ERK_ERR_NOT_FOUND` without one.
 */
ErkStatus erk_node_attr(ErkApp *app,
                        ErkNodeId node_id,
                        ErkStr name,
                        char *buf,
                        size_t cap,
                        size_t *len);

/*
 Set property `name` of element `node`'s inline style to `value`, as
 CSSOM's `element.style.setProperty` does: a shorthand sets its
 longhands, `--name` is a custom property, an empty value removes the
 property. The `style` attribute is rewritten with it.
 `ERK_ERR_INVALID_ARGUMENT` for a name Erk does not know or a value the
 property does not take; nothing changes then.
 */
ErkStatus erk_node_set_style_property(ErkApp *app, ErkNodeId node_id, ErkStr name, ErkStr value);

/*
 Remove property `name` (a shorthand with its longhands) from element
 `node`'s inline style.
 */
ErkStatus erk_node_remove_style_property(ErkApp *app, ErkNodeId node_id, ErkStr name);

/*
 Property `name` of element `node`'s inline style, serialized as CSSOM's
 `getPropertyValue` does, into `buf` as `erk_node_text` writes it;
 `ERK_ERR_NOT_FOUND` when it is not set.
 */
ErkStatus erk_node_style_property(ErkApp *app,
                                  ErkNodeId node_id,
                                  ErkStr name,
                                  char *buf,
                                  size_t cap,
                                  size_t *len);

ErkStatus erk_node_add_class(ErkApp *app, ErkNodeId node_id, ErkStr class_);

ErkStatus erk_node_remove_class(ErkApp *app, ErkNodeId node_id, ErkStr class_);

/*
 `*out` is 1 if element `node`'s classes hold `class`, else 0.
 */
ErkStatus erk_node_has_class(ErkApp *app, ErkNodeId node_id, ErkStr class_, uint32_t *out);

/*
 Every element inside `scope` (`ERK_NODE_NONE`: the document) matching
 `selector`, in document order, into `out`: all of them or none.
 `*len` is always how many there are; `ERK_ERR_BUFFER_TOO_SMALL` when
 `cap` is less.
 */
ErkStatus erk_query_all(ErkApp *app,
                        ErkNodeId scope,
                        ErkStr selector,
                        ErkNodeId *out,
                        size_t cap,
                        size_t *len);

/*
 Apply `count` mutations in order, in one call (p1-contract §10). The ids
 the batch created go to `created` (`count` entries, `ERK_NODE_NONE` for
 mutations that create nothing; may be NULL). The first that fails stops
 the batch: its position goes to `*failed_at` (may be NULL) and its
 status is returned; the ones before it stay applied.
 */
ErkStatus erk_apply(ErkApp *app,
                    const ErkMutation *mutations,
                    size_t count,
                    ErkNodeId *created,
                    size_t *failed_at);

/*
 Call `fn(user_data, app, event)` when an event of `kind` reaches `node`
 at its target or bubbling up; `destroy(user_data)` once, when the
 subscription ends (`erk_off`, the node leaving the document, the app's
 end). A call that fails takes nothing: `user_data` stays the host's.
 */
ErkStatus erk_on(ErkApp *app,
                 ErkNodeId node_id,
                 uint32_t kind,
                 ErkEventFn function,
                 void *user_data,
                 ErkDestroyFn destroy,
                 ErkSubscription *out);

/*
 `erk_on` in the capture phase: on the way down, and at the target before
 the bubble subscriptions there.
 */
ErkStatus erk_on_capture(ErkApp *app,
                         ErkNodeId node_id,
                         uint32_t kind,
                         ErkEventFn function,
                         void *user_data,
                         ErkDestroyFn destroy,
                         ErkSubscription *out);

ErkStatus erk_off(ErkApp *app, ErkSubscription subscription);

/*
 Inside an event callback: the event goes no further than this node.
 */
ErkStatus erk_event_stop_propagation(ErkApp *app);

ErkStatus erk_node_parent(ErkApp *app, ErkNodeId node_id, ErkNodeId *out);

/*
 `node`'s child at `index`; `*out` is `ERK_NODE_NONE` past the last.
 */
ErkStatus erk_node_child_at(ErkApp *app, ErkNodeId node_id, size_t index, ErkNodeId *out);

ErkStatus erk_node_child_count(ErkApp *app, ErkNodeId node_id, size_t *out);

/*
 `ERK_NODE_*`.
 */
ErkStatus erk_node_kind(ErkApp *app, ErkNodeId node_id, uint32_t *out);

/*
 An element's tag name; `ERK_ERR_NOT_FOUND` for other nodes.
 */
ErkStatus erk_node_tag(ErkApp *app, ErkNodeId node_id, char *buf, size_t cap, size_t *len);

ErkStatus erk_node_attribute_count(ErkApp *app, ErkNodeId node_id, size_t *out);

/*
 An element's attribute at `index`, in the order written; free both
 strings. `ERK_ERR_NOT_FOUND` past the last.
 */
ErkStatus erk_node_attribute_at(ErkApp *app,
                                ErkNodeId node_id,
                                size_t index,
                                ErkString *name,
                                ErkString *value);

/*
 `node`'s box in the last frame; `ERK_ERR_NOT_FOUND` without one.
 */
ErkStatus erk_node_box(ErkApp *app, ErkNodeId node_id, ErkBox *out);

/*
 `node`'s computed style as `name: value;` lines; free the string.
 */
ErkStatus erk_node_computed_style(ErkApp *app, ErkNodeId node_id, ErkString *out);

/*
 The topmost node at `x`, `y` in the last frame; `ERK_NODE_NONE` if none.
 */
ErkStatus erk_inspect_at(ErkApp *app, float x, float y, ErkNodeId *out);

/*
 Highlight `node`'s boxes over the page; `ERK_NODE_NONE` clears.
 */
ErkStatus erk_highlight(ErkApp *app, ErkNodeId node_id);

/*
 How long the last painted frame's stages took; `ERK_ERR_NOT_FOUND`
 before the first.
 */
ErkStatus erk_last_frame_timings(ErkApp *app, ErkFrameTimings *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ERK_H */
